export const DATA_FETCH_PENDING = "_PENDING";
export const DATA_FETCH_FULFILLED = "_FULFILLED";
export const DATA_FETCH_REJECTED = "_REJECTED";
export const DATA_FETCH_DATA_PROP = "data";

export const OFFLINE_FIRST_POSTFIX = "_OFFLINE_FIRST";

export const CHECK_IF_EMAIL_IS_DEMO = "CHECK_IF_EMAIL_IS_DEMO";

export const USER_LOGIN = "USER_LOGIN";
export const USER_SIGNUP = "USER_SIGNUP";
export const USER_LOGOUT = "USER_LOGOUT";
export const FETCH_USER_ADDRESS = "FETCH_USER_ADDRESS";
export const SET_USER_DELIVERY_CONDITION = "SET_USER_DELIVERY_CONDITION";
export const SET_USER_DEFAULT_ADDRESS = "SET_USER_DEFAULT_ADDRESS";
export const FETCH_USER_PAYMENT_METHODS = "FETCH_USER_PAYMENT_METHODS";
export const ADD_USER_PAYMENT_METHOD = "ADD_USER_PAYMENT_METHOD";
export const EDIT_USER_PAYMENT_METHOD = "EDIT_USER_PAYMENT_METHOD";
export const FETCH_USER_REWARDS = "FETCH_USER_REWARDS";
export const EDIT_USER_NAME = "EDIT_USER_NAME";
export const EDIT_USER_PASSWORD = "EDIT_USER_PASSWORD";
export const EDIT_USER_EMAIL = "EDIT_USER_EMAIL";
export const VERIFY_USER_EMAIL = "VERIFY_USER_EMAIL";
export const FETCH_USER_REFERRAL = "FETCH_USER_REFERRAL";
export const SEND_PASSWORD_RECOVERY = "SEND_PASSWORD_RECOVERY";
export const RECOVER_PASSWORD = "RECOVER_PASSWORD";

export const SET_ACCOUNT_BAN = "SET_ACCOUNT_BAN";

export const FETCH_MENU_ITEMS = "FETCH_MENU_ITEMS";
export const FETCH_MENU_ITEM_INSTRUCTIONS = "FETCH_MENU_ITEM_INSTRUCTIONS";
export const FETCH_MENU_ITEM_DATA = "FETCH_MENU_ITEM_DATA";
export const TOGGLE_MENU_ITEM_FAVORITE = "TOGGLE_MENU_ITEM_FAVORITE";
export const SET_USER_FAVORITE_MENU_ITEMS = "SET_USER_FAVORITE_MENU_ITEMS";

export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const CLEAR_SHOPPING_CART = "CLEAR_SHOPPING_CART";
export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART";
export const SUBMIT_SHOPPING_CART = "SUBMIT_SHOPPING_CART";
export const FETCH_USER_ORDER_HISTORY = "FETCH_USER_ORDER_HISTORY";
export const CANCEL_ORDER = "CANCEL_ORDER";

export const FETCH_CALENDAR_EVENTS = "FETCH_CALENDAR_EVENTS";

export const FETCH_RESERVE_HISTORY = "FETCH_RESERVE_HISTORY";
export const CANCEL_RESERVE = "CANCEL_RESERVE";
export const ADD_RESERVE = "ADD_RESERVE";
export const CHECK_RESRVE_AVAILABILITY = "CHECK_RESRVE_AVAILABILITY";

export const SET_NOTIFICATION_INSTANCE_TOKEN =
    "SET_NOTIFICATION_INSTANCE_TOKEN";
export const SET_NOTIFICATION_INSTANCE_TOKEN_SENT_TO_SERVER =
    "SET_NOTIFICATION_INSTANCE_TOKEN_SENT_TO_SERVER";